### ISSUE TITLE
Investigate changing "Overview" for the "Guide section title"

### ISSUE THREAD

**Issue by OliverHannan** [localgovdrupal/localgov_guides#39] opened 2021-03-12 16:01 UTC
Guide overview pages have the word 'Overview' hard-coded, but we want them to use the page title defined by a content designer

![image](https://user-images.githubusercontent.com/47107641/110965780-70505c80-834c-11eb-9cdf-a6eb504ede2a.png)

**Comment by keelanfh** [comment] 2023-05-18 18:42
Closed as duplicate of #113

**Closed by keelanfh** 2023-05-18 18:42 UTC
