### ISSUE TITLE
Make guide overview title on pages optional

### ISSUE THREAD

**Issue by OliverHannan** [localgovdrupal/localgov_guides#41] opened 2021-03-12 16:16 UTC
**Guides**

The first page always has Overview as the title, but we don't always need an overview and end up just having an intro unnecessarily, could we make it so we can make the overview pages just the first page in the guide?

**There is a workaround**

To hide the overview header in the meantime use the following in the 'body' wysiwyg :

<style type="text/css">
main > h2:first-child {display:none;}
</style>

**Comment by keelanfh** [comment] 2023-06-02 09:26
Closed as duplicate of #113

**Closed** 2023-06-02 09:26 UTC
